---
- hosts: localhost
  gather_facts: False
  environment:
    GOVC_USERNAME: '{{ vcenter.admin_username }}'
    GOVC_PASSWORD: '{{ vcenter.admin_password }}'
    GOVC_URL: 'https://{{ vcenter.ip }}'
    GOVC_DATACENTER: '{{ vcenter.datacenter }}'
    GOVC_INSECURE: 1

  tasks:
    - name: Download govc clients
      become: true
      ansible.builtin.unarchive:
        src: '{{ download.govc }}'
        dest: /usr/local/bin
        remote_src: true
        mode: '0755'

    - name: Create OCP 4 vCenter Role
      ansible.builtin.import_playbook: vcenter_roles.yml

    - name: Apply OCP 4 vCenter Permissions for precreated VM Folder
      ansible.builtin.import_playbook: precreated_folder.yml
      when: openshift.installer_created_folder == False

    - name: Apply OCP 4 vCenter Permissions for installer created VM Folder
      ansible.builtin.import_playbook: created_folder.yml
      when: openshift.installer_created_folder == True
