---
- name: Download govc clients
  become: true
  ansible.builtin.unarchive:
    src: '{{ download.govc }}'
    dest: /usr/local/bin
    remote_src: true
    mode: '0755'

- name: Create OCP 4 vCenter Role
  ansible.builtin.import_playbook: vcenter_roles.yml

- name: Apply OCP 4 vCenter Permissions for precreated VM Folder
  ansible.builtin.import_playbook: precreated_folder.yml
  when: openshift.installer_created_folder == False

- name: Apply OCP 4 vCenter Permissions for installer created VM Folder
  ansible.builtin.import_playbook: created_folder.yml
  when: openshift.installer_created_folder == True
